"""Generate tracked tool contract projections from the canonical typed definitions."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import yaml

from poker_deliberation.schemas import ToolResult
from poker_deliberation.tools.contracts import ToolContract, tool_contracts

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "tools" / "manifest.yaml"
DOC_PATH = ROOT / "docs" / "tool-contracts.md"
CANONICAL_SOURCE = "poker_deliberation.tools.contracts.tool_contracts"


def manifest_document() -> dict[str, object]:
    return {
        "schema_version": 2,
        "canonical_source": CANONICAL_SOURCE,
        "policy": {
            "default_timeout_seconds": 30,
            "default_input_limit_bytes": 1_000_000,
            "default_output_limit_bytes": 1_000_000,
            "default_run_limit_bytes": 10_000_000,
            "external_execution_requires_approval": True,
            "legacy_exactness_field": "compatibility projection; use numeric_exactness for v2",
        },
        "tool_result_schema": ToolResult.model_json_schema(),
        "tools": [contract.manifest_entry() for contract in tool_contracts()],
    }


def render_manifest() -> str:
    body = yaml.safe_dump(
        manifest_document(),
        allow_unicode=True,
        sort_keys=False,
        width=100,
    )
    return "# Generated by scripts/generate_tool_contracts.py; do not edit manually.\n" + body


def _field_summary(schema: dict[str, Any]) -> str:
    required = set(schema.get("required", []))
    properties = schema.get("properties", {})
    if not isinstance(properties, dict) or not properties:
        return "なし"
    return ", ".join(f"`{name}`{' (required)' if name in required else ''}" for name in properties)


def _json_inline(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def _render_contract(contract: ToolContract) -> list[str]:
    input_schema = contract.input_model.model_json_schema()
    output_schema = contract.output_model.model_json_schema()
    tolerance = contract.tolerance.model_dump(mode="json") if contract.tolerance else None
    lines = [
        f"## `{contract.name}`",
        "",
        contract.purpose,
        "",
        f"- Tool version: `{contract.version}`",
        f"- Contract version: `{contract.contract_version}`",
        "- Numeric exactness: "
        + ", ".join(f"`{item.value}`" for item in contract.numeric_exactness_modes),
        f"- Input model: `{contract.input_model.__name__}`",
        f"- Input fields: {_field_summary(input_schema)}",
        f"- Output model: `{contract.output_model.__name__}`",
        f"- Output fields: {_field_summary(output_schema)}",
        f"- Assumptions: {_json_inline(list(contract.assumptions))}",
        f"- Preconditions: {_json_inline(list(contract.preconditions))}",
        f"- Limits: {_json_inline(contract.limits)}",
        f"- Units: {_json_inline(contract.units)}",
        f"- Failure modes: {_json_inline(list(contract.failure_modes))}",
        f"- Verification checks: {_json_inline(list(contract.verification_checks))}",
        f"- Tolerance: {_json_inline(tolerance)}",
        f"- Model qualifier: {_json_inline(contract.model_qualifier)}",
        "",
    ]
    return lines


def render_docs() -> str:
    contracts = tool_contracts()
    lines = [
        "# Tool contracts",
        "",
        "<!-- Generated by scripts/generate_tool_contracts.py; do not edit manually. -->",
        "",
        f"Canonical source: `{CANONICAL_SOURCE}`.",
        "",
        "The tracked manifest contains the complete JSON Schema for every input/output model. "
        "This document is the human-readable projection of the same definitions.",
        "",
        "## Common result contract",
        "",
        "Version 2 results add `numeric_exactness`, `contract_version`, model/method fields, "
        "tool-specific verification metadata, and complete approximation metadata. The original "
        "three-value `exactness` remains a compatibility projection.",
        "",
        "`approximate` success requires method, stochastic flag, seed when stochastic, positive "
        "samples or iterations, an interval or error metadata, and a stopping condition. "
        "`failed` and `unavailable` cannot carry successful numeric exactness.",
        "",
        f"Registered tool count: `{len(contracts)}`.",
        "",
    ]
    for contract in contracts:
        lines.extend(_render_contract(contract))
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the tracked projections differ from the canonical contracts",
    )
    args = parser.parse_args(argv)
    expected_manifest = render_manifest()
    expected_docs = render_docs()
    if args.check:
        stale = [
            str(path)
            for path, expected in (
                (MANIFEST_PATH, expected_manifest),
                (DOC_PATH, expected_docs),
            )
            if not path.is_file() or path.read_text(encoding="utf-8") != expected
        ]
        if stale:
            raise SystemExit(f"generated tool contract projection is stale: {', '.join(stale)}")
        return 0
    MANIFEST_PATH.write_text(expected_manifest, encoding="utf-8", newline="\n")
    DOC_PATH.write_text(expected_docs, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
